export const GET_DEPLOYMENTS = "GET_DEPLOYMENTS";
export const DELETE_DEPLOYMENT = "DELETE_DEPLOYMENT";
export const ADD_DEPLOYMENT = "ADD_DEPLOYMENT";


export const GET_TEMPLATES = "GET_TEMPLATES";
export const ADD_TEMPLATE = "ADD_TEMPLATE";
export const ADD_TEMPLATE_VERSION = "ADD_TEMPLATE_VERSION";

export const ADD_MESSAGE = "ADD_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const START_LOADING_DATA = "START_LOADING_DATA";
export const END_LOADING_DATA = "END_LOADING_DATA";